// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPrize(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.Prize>;

export function AddUser(arg1:string,arg2:string):Promise<main.User>;

export function DeleteAllUsers():Promise<void>;

export function DeletePrize(arg1:string):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function DrawLottery(arg1:string):Promise<main.DrawResult>;

export function GetAvailableUsers():Promise<Array<main.User>>;

export function GetPrizes():Promise<Array<main.Prize>>;

export function GetStatistics():Promise<Record<string, any>>;

export function GetUsers():Promise<Array<main.User>>;

export function GetWonUsers():Promise<Array<Record<string, any>>>;

export function ImportUsersFromCSV(arg1:string):Promise<number>;

export function ResetLottery():Promise<void>;

export function UpdatePrize(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;
