// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPrize(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddPrize'](arg1, arg2, arg3, arg4);
}

export function AddUser(arg1, arg2) {
  return window['go']['main']['App']['AddUser'](arg1, arg2);
}

export function DeleteAllUsers() {
  return window['go']['main']['App']['DeleteAllUsers']();
}

export function DeletePrize(arg1) {
  return window['go']['main']['App']['DeletePrize'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function DrawLottery(arg1) {
  return window['go']['main']['App']['DrawLottery'](arg1);
}

export function GetAvailableUsers() {
  return window['go']['main']['App']['GetAvailableUsers']();
}

export function GetPrizes() {
  return window['go']['main']['App']['GetPrizes']();
}

export function GetStatistics() {
  return window['go']['main']['App']['GetStatistics']();
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function GetWonUsers() {
  return window['go']['main']['App']['GetWonUsers']();
}

export function ImportUsersFromCSV(arg1) {
  return window['go']['main']['App']['ImportUsersFromCSV'](arg1);
}

export function ResetLottery() {
  return window['go']['main']['App']['ResetLottery']();
}

export function UpdatePrize(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdatePrize'](arg1, arg2, arg3, arg4, arg5);
}
